package io.ancoris.mcp.connector;

import org.junit.jupiter.api.Test;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

class ContentEncryptorTest {

    // 64 hex chars = 32 bytes (AES-256 key)
    private static final String TEST_KEY =
            "0101010101010101010101010101010101010101010101010101010101010101";

    private final ContentEncryptor encryptor = new ContentEncryptor(TEST_KEY);

    // -----------------------------------------------------------------------
    // Round-trip: decrypt(encrypt(text)) == text
    // -----------------------------------------------------------------------

    @Test
    void roundTrip_decryptedEqualsOriginal() {
        String original = "Le bilan énergétique des datacenters normands.";

        byte[] encrypted = encryptor.encrypt(original);
        String decrypted = encryptor.decrypt(encrypted);

        assertThat(decrypted).isEqualTo(original);
    }

    // -----------------------------------------------------------------------
    // Random IV: two encryptions of the same plaintext produce different bytes
    // -----------------------------------------------------------------------

    @Test
    void encrypt_randomIv_producedDifferentCiphertexts() {
        String plaintext = "same text";

        byte[] first = encryptor.encrypt(plaintext);
        byte[] second = encryptor.encrypt(plaintext);

        assertThat(first).isNotEqualTo(second);
    }

    // -----------------------------------------------------------------------
    // Tampered bytes → SecurityException (GCM tag mismatch)
    // -----------------------------------------------------------------------

    @Test
    void decrypt_tamperedCiphertext_throwsSecurityException() {
        byte[] encrypted = encryptor.encrypt("sensitive");
        // Flip one byte in the ciphertext portion (after the 12-byte IV)
        encrypted[15] ^= 0xFF;

        assertThatThrownBy(() -> encryptor.decrypt(encrypted))
                .isInstanceOf(SecurityException.class)
                .hasMessageContaining("authentication failed");
    }

    // -----------------------------------------------------------------------
    // Wrong key → SecurityException (GCM tag mismatch)
    // -----------------------------------------------------------------------

    @Test
    void decrypt_wrongKey_throwsSecurityException() {
        // 64 valid hex chars, different from TEST_KEY (0101...)
        String otherKey = "abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789";
        ContentEncryptor otherEncryptor = new ContentEncryptor(otherKey);

        byte[] encrypted = encryptor.encrypt("data encrypted with TEST_KEY");

        assertThatThrownBy(() -> otherEncryptor.decrypt(encrypted))
                .isInstanceOf(SecurityException.class);
    }

    // -----------------------------------------------------------------------
    // Short key (< 64 hex chars) → IllegalStateException at construction
    // -----------------------------------------------------------------------

    @Test
    void constructor_shortKey_throwsIllegalStateException() {
        assertThatThrownBy(() -> new ContentEncryptor("deadbeef"))
                .isInstanceOf(IllegalStateException.class)
                .hasMessageContaining("64 hex characters");
    }

    // -----------------------------------------------------------------------
    // Cross-language wire compatibility: Java must decrypt bytes produced by
    // the Rust ingestion/src/crypto.rs encrypt_with_iv() using the same key.
    //
    // Test vector generated by:
    //   cargo test --manifest-path ingestion/Cargo.toml cross_lang_vector -- --nocapture
    //   key = [0x01; 32], iv = [0x02; 12], plaintext = "hello from rust"
    // Wire format: [12B IV][ciphertext + 16B GCM tag] — identical in both runtimes.
    // -----------------------------------------------------------------------

    @Test
    void rustWireFormat_javaCanDecrypt() {
        String rustKey = "0101010101010101010101010101010101010101010101010101010101010101";
        ContentEncryptor rustEncryptor = new ContentEncryptor(rustKey);

        byte[] rustWireBytes = java.util.HexFormat.of().parseHex(
                "0202020202020202020202026fb3a5252577a78fbca19cba29d4b6563efaae01c66c1df66b7a6e44e7a1da");

        String decrypted = rustEncryptor.decrypt(rustWireBytes);

        assertThat(decrypted).isEqualTo("hello from rust");
    }
}
